/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pruebapaneles;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import javax.swing.*;

/**
 *
 * @author Adrian
 */
public class fran1 extends javax.swing.JFrame {

      private JPanel currentPanel; // Mantiene una referencia al panel actualmente visible

    /**
     * Creates new form fran1
     */
    public fran1() {
        //initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
         // creo mi objeto con clase Toolkit
        Toolkit mipantalla= Toolkit.getDefaultToolkit();
        // Uso metodo "getScreenSize" para sacar el tamaño de la pantalla(nos devuelve un objeto de tipo "Dimension")
        Dimension tamanoPantalla= mipantalla.getScreenSize();
        // "Dimension" nos da 2 valores int para altura y ancho. Declaramos variables para obtener los tamaños
        int alturaPantalla= tamanoPantalla.height;
        int anchoPantalla= tamanoPantalla.width;
        
        // Indicamos tamaño pantalla con los valores de dimension/2 para que nos quede de media pantalla
        setSize(anchoPantalla/2, alturaPantalla/2);
        // Coloco la pantalla en /4 /4 para que quede centrado
        setLocation(anchoPantalla/4,alturaPantalla/4);
        // Hacemos que no se pueda redimensionar
        setResizable(false);
        // Se tiene que poder ver
        //setVisible(true);
        //Titulo menu principal
        setTitle("Menu principal de la NASA");
         
        setLayout(new FlowLayout());
        
        
        
        
    }
    //Movida sacado del partitaviewer
                private void setPanel(JPanel panel) {
        if (currentPanel != null) {
        getContentPane().remove(currentPanel); // Elimina el panel actual
        }
        currentPanel = panel; // Actualiza la referencia al panel actual
        getContentPane().add(currentPanel, BorderLayout.CENTER);
        revalidate();
        repaint(); // Asegura que el área donde estaba el panel anterior se redibuje
        }
                
               
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /*
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents
    */
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
